# Use an official Java runtime as a parent image
FROM amazoncorretto:21.0.4-alpine3.18

ENV UID 1000
ENV GID 1000

RUN addgroup -g ${GID} -S backend &&\
    adduser -D -h /home/backend -u ${UID} -G backend -S backend &&\
    # install -d -m 0755 -o www-data -g www-data /home/www-data &&\
    chown --changes --silent --no-dereference --recursive ${UID}:${GID} \
    /home/backend

USER backend

WORKDIR /home/backend/app
# Copy the JAR file into the container
# COPY target/containerize-java-spring-0.0.1-SNAPSHOT.jar app.jar
# ARG JAR_FILE=*.jar
# COPY ${JAR_FILE} app.jar
COPY . .
# Expose the port that the application will run on
EXPOSE 8080
# Authorization env
ENV AUTHORIZATION ""
# Run the JAR file
# ENTRYPOINT ["java", "-jar", "app.jar"]
CMD ["./mvnw", "spring-boot:run"]
